# netlify.toml

# This file tells Netlify how to build your site and where to find your serverless functions.

[build]
  command = "npm run build"
  publish = "build"  # ← Correct for Create React App

[functions]
  directory = "netlify/functions"