import React, { useState, useRef } from 'react';

const MAX_IMAGES_FREE = 3;
const MAX_IMAGES_PRO = 10;
const MAX_VIDEOS_PRO = 2;

const SpicyLister = () => {
  // Media
  const [images, setImages] = useState([]);
  const [videos, setVideos] = useState([]);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [processing, setProcessing] = useState(false);

  // Pro/Modal states
  const [showProModal, setShowProModal] = useState(false);
  const [showCoffeeConfirm, setShowCoffeeConfirm] = useState(false);
  const [isPro, setIsPro] = useState(false);
  const [proExpiryDate, setProExpiryDate] = useState(null);

  // File input refs
  const imgInputRef = useRef();
  const vidInputRef = useRef();

  // Upload handlers
  const handleImages = async (e) => {
    const files = Array.from(e.target.files);
    const max = isPro ? MAX_IMAGES_PRO : MAX_IMAGES_FREE;
    if (images.length + files.length > max) {
      setError(`Max ${max} images${isPro ? '' : ' (PRO gets 10)'}`);
      return;
    }
    setError('');
    // Show previews
    const newImgs = files.map(file => ({
      file,
      preview: URL.createObjectURL(file),
      id: Date.now() + Math.random()
    }));
    setImages(imgs => [...imgs, ...newImgs]);
  };

  const handleVideos = async (e) => {
    const files = Array.from(e.target.files);
    if ((videos.length + files.length) > MAX_VIDEOS_PRO && isPro) {
      setError('Max 2 videos per listing (PRO)');
      return;
    }
    setError('');
    const newVids = files.map(file => ({
      file,
      preview: URL.createObjectURL(file),
      id: Date.now() + Math.random()
    }));
    setVideos(vids => [...vids, ...newVids]);
  };

  // Remove media
  const removeMedia = (id, type) => {
    if (type === 'img') setImages(imgs => imgs.filter(i => i.id !== id));
    else setVideos(vids => vids.filter(v => v.id !== id));
  };

  // AI analyze mock - replace with real Gemini call later!
  const analyzeMedia = async () => {
    if (images.length === 0 && videos.length === 0) {
      setError('Upload at least one image or video!');
      return;
    }
    setProcessing(true);
    setTimeout(() => {
      setProcessing(false);
      setResult({
        title: isPro, "🔥 Premium NeuroSpicy LED String Lights - USB, Mood, ADHD-Friendly!" :
          "LED String Lights, Great for Mood Lighting",
        description: isPro
          ? `🌶️ Listing generated by SpicyLister PRO!\n\n✔️ 2M RGB fairy lights with remote\n✔️ USB powered - plug anywhere\n✔️ Perfect for bedroom, van, shed, comedy shows\n\nProfessionally tested by a neurospicy mind!`,
          : "LED string lights, used but working. Plug via USB, changes colour. Fun for mood lighting.",
        keywords: isPro
          ? ["led string", "adhd", "fairy lights", "mood lighting", "neurospicy", "van life"]
          : ["led", "lights", "mood"],
        price: isPro ? "£12.99-15.99" : "£8.99",
      });
    }, 1800);
  };

  // PRO MODAL unlock
  const handleCoffeeSupport = () => {
    setError('');
    window.open('https://buymeacoffee.com/chrispteemagician', '_blank');
    setTimeout(() => setShowCoffeeConfirm(true), 7000);
  };
  const handleCoffeeConfirm = (confirmed) => {
    setShowCoffeeConfirm(false);
    if (confirmed) {
      const d = new Date();
      d.setMonth(d.getMonth() + 1);
      setIsPro(true);
      setProExpiryDate(d);
      alert(`🎉 PRO for 1 month! Valid until ${d.toLocaleDateString()}`);
      setShowProModal(false);
    }
  };

  // Reset all
  const reset = () => {
    setImages([]); setVideos([]); setResult(null); setError('');
  };

  return (
  <div style={{ fontFamily: 'sans-serif', background: "#fffaf3", minHeight: "100vh", paddingBottom: 80 }}>
    {/* HEADER / logo / tagline */}
    <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginTop: 16, marginBottom: 10 }}>
      <img src="/spicylister-logo.png" alt="SpicyLister Logo"
        style={{height: 56, width: 56, borderRadius:16, boxShadow: '0 1px 12px #e87413', background:'#fffbe7'}}
      />
      <div>
        <h1 style={{margin: 0, color: "#e87413", fontFamily: "cursive", letterSpacing: 2}}>🌶️ SpicyLister 1.2</h1>
        <div style={{fontWeight:"bold", color:"#633202", fontSize:17}}>Sell Clutter Without a Stutter!</div>
        <div style={{color:"#b4561f", fontSize:15, marginTop:3}}>
          Dopamine hits in 60 seconds – By the NeuroSpicy for Anyne who needs a hand listing stuff and making a few bob.
        </div>
      </div>
    </div>

    {/* Main upload UI */}
    <div style={{
      border: "2px dashed #e87413", background: "#fff8f2", borderRadius:14, padding:24, margin:"28px 0 12px 0"
    }}>
      <b>Photos ({images.length}/{isPro ? MAX_IMAGES_PRO : MAX_IMAGES_FREE})</b>
      <div style={{display:"flex",flexWrap:"wrap",gap:7,marginTop:4,marginBottom:10}}>
        {images.map(img=>(
          <div key={img.id} style={{position:"relative"}}>
            <img src={img.preview} alt="" style={{height:48, width:48, borderRadius:5, border:"1px solid #ffa75c"}} />
            <button title="Remove" onClick={()=>removeMedia(img.id,'img')}
              style={{position:"absolute",top:-7,right:-7,background:"#fa5027",color:"#fff",border:"none",borderRadius:"50%",width:22,height:22,cursor:"pointer"}}>✖</button>
          </div>
        ))}
        {(images.length < (isPro ? MAX_IMAGES_PRO : MAX_IMAGES_FREE)) &&
          <button onClick={()=>imgInputRef.current.click()} style={{
            height:48,width:48,borderRadius:5,
            border:"2px dashed #e87413",fontSize:30,background:"#fffbe9",color:"#e87413",cursor:"pointer"
          }}>+</button>
        }
        <input
          ref={imgInputRef}
          type="file"
          accept="image/*"
          multiple
          style={{display:"none"}}
          onChange={handleImages}
        />
      </div>
      <b>Videos ({videos.length}/{MAX_VIDEOS_PRO} PRO)</b>
      <div style={{display:"flex", flexWrap:"wrap", gap:7,marginTop:4,marginBottom:10}}>
        {videos.map(vid=>(
          <div key={vid.id} style={{ position: "relative" }}>
            <video src={vid.preview} style={{height:48,width:84,borderRadius:5,background:"#eee"}} controls/>
            <button title="Remove" onClick={()=>removeMedia(vid.id,'vid')}
              style={{position:"absolute",top:-7,right:-7,background:"#fa5027",color:"#fff",border:"none",borderRadius:"50%",width:22,height:22,cursor:"pointer"}}>✖</button>
          </div>
        ))}
        {(isPro && videos.length < MAX_VIDEOS_PRO) &&
          <button onClick={()=>vidInputRef.current.click()} style={{
            height:48,width:84,borderRadius:5,
            border:"2px dashed #e87413",fontSize:24,background:"#fffbe9",color:"#e87413",cursor:"pointer"
          }}>+</button>
        }
        <input
          ref={vidInputRef}
          type="file"
          accept="video/*"
          multiple
          style={{display:"none"}}
          onChange={handleVideos}
        />
      </div>
      {error && <div style={{ color:'red', fontWeight:'bold', margin:'8px 0 0 0' }}>{error}</div>}
    </div>

    {/* Generate + Unlock Pro */}
    <div style={{margin:'24px 0'}}>
      <button
        style={{
          fontSize: 22, padding: "14px 34px", background:'linear-gradient(90deg,#ff9001,#fa3b38,#fcb900,#f74d12)', color:'#fff',
          border:'none', borderRadius:12, cursor:'pointer', fontWeight:"bold", letterSpacing:1, boxShadow:"0 1px 12px #e87413",display:"flex",alignItems:"center"
        }}
        onClick={analyzeMedia}
        disabled={processing}
      >
        <img src="/spicylister-logo.png" alt="" style={{height:32,width:32,borderRadius:5,marginRight:8}}/> Generate!
      </button>
      <button
        onClick={()=>setShowProModal(true)}
        style={{ marginLeft:15, background:'#fd0', color:'#222',padding:"10px 24px",fontWeight:'bold',borderRadius:10,border:"none",fontSize:"1.05em",cursor:"pointer" }}>
        Unlock PRO (1mo, BuyMeACoffee)
      </button>
    </div>
    {isPro && proExpiryDate && <div style={{color:'green',fontWeight:"bold",marginBottom:18}}>
      ⭐ PRO is active until {proExpiryDate.toLocaleDateString()}!
    </div>}

    {/* Show result */}
    {processing && <div style={{fontWeight:"bold",color:"#fa5027",margin:"28px 0",fontSize:19}}>Analyzing with AI…</div>}
    {result &&
      <div style={{
         margin:"32px 0",background:"#ffefd9",borderRadius:16,padding:"24px 28px",boxShadow:"0 2px 12px #ffe7b0"
      }}>
        <h2 style={{color:"#b4561f",marginTop:0}}>🎉 AI Listing Generated:</h2>
        <div style={{fontWeight:600,fontSize:22,margin:"10px 0"}}>{result.title}</div>
        <div style={{whiteSpace:"pre-wrap",margin:"10px 0 18px 0"}}>{result.description}</div>
        <div>
          <span style={{background:"#232",color:"#fff",borderRadius:6,padding:"3px 8px",marginRight:12}}>Keywords:</span>
          {result.keywords.map(kw=>(
            <span key={kw} style={{background:"#faedbe",borderRadius:4,padding:"2px 7px",margin:"0 4px",color:"#884f04"}}>{kw}</span>
          ))}
        </div>
        <div style={{margin:"14px 0 8px 0",fontWeight:"bold",fontSize:18,background:"#fae7b4",display:"inline-block",padding:"5px 16px",borderRadius:7}}>
          Suggest Price: {result.price}
        </div>
        <br/>
        <button onClick={reset} style={{
          marginTop:'12px',background:'#fa5027',color:'#fff',border:'none',borderRadius:8,padding:"9px 22px",fontWeight:"bold",fontSize:17,cursor:"pointer"
        }}>
          New Listing
        </button>
      </div>
    }

    {/* Modals */}
    {showProModal && (
      <div style={{
        position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh',
        background: 'rgba(0,0,0,0.7)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:9999
      }}>
        <div style={{
          background:'#fff',borderRadius:14,padding:32,maxWidth:400,textAlign:'center',boxShadow:'0 2px 18px #fd0'
        }}>
          <h2 style={{color:"#d85901"}}>Support the Van Life, Unlock PRO!</h2>
          <p>
            Buy me a coffee (or Ko-fi below) at any amount for 1 month PRO.<br/>
            After donating, click "Yes" on the next popup!
          </p>
          <button
            onClick={handleCoffeeSupport}
            style={{margin:18,padding:18,borderRadius:8,background:'#fd0',fontSize:16,fontWeight:"bold"}}
          >☕ Buy Me a Coffee (1mo Pro)</button>
          <br/>
          <a href="https://ko-fi.com/zoom" target="_blank" rel="noopener noreferrer"
            style={{display:'inline-block',margin:18,color:"#29abe0",fontWeight:700,textDecoration:"underline",fontSize:16}}>
            Or support on Ko-fi (click here)
          </a>
          <br/><br/>
          <button
            onClick={()=>setShowProModal(false)}
            style={{marginTop:24,fontSize:16}}>Cancel</button>
        </div>
      </div>
    )}
    {showCoffeeConfirm && (
      <div style={{
        position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh',
        background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999
      }}>
        <div style={{
          background: 'white', padding: 24, borderRadius: 8, width: 340, textAlign: 'center', boxShadow: '0 6px 28px #fdbd2c'
        }}>
          <div style={{ marginBottom: 18, fontWeight: 'bold', fontSize:18, color: "#b4561f" }}>
            Did you buy me a coffee or support?
          </div>
          <button style={{ margin: '0 18px', fontSize: 16, padding: 10, background: "#fd0", fontWeight:"bold", border:"none", borderRadius:5 }}
            onClick={() => handleCoffeeConfirm(true)}>
            Yes
          </button>
          <button style={{ margin: '0 18px', fontSize: 16, padding: 10, background: "#fa5027", color:"#fff",border:"none", borderRadius:5 }}
            onClick={() => handleCoffeeConfirm(false)}>
            No
          </button>
        </div>
      </div>
    )}

    {/* Footer */}
    <div style={{
      position: "fixed", width: "100%", left: 0, bottom: 0, background: "#fff1e3", padding: "10px 0",
      color: "#7b3a0b", fontWeight: 500, textAlign: "center", fontFamily: "monospace", fontSize: 15, borderTop: "1px solid #ffb56b"
    }}>
      Made with <span style={{color:"#e74c3c"}}>❤️</span> by Chris P Tee – Vanlife + Comedy + Magic + Code
    </div>
  </div>
  );
};

export default SpicyLister;
