# netlify.toml

# This file tells Netlify how to build your site and where to find your serverless functions.

[build]
  # We leave the command blank because we are building the site locally
  # and only uploading the final "dist" folder.
  command = ""
  
  # This is the directory where the pre-built files are located.
  publish = "dist"

[functions]
  # This tells Netlify to look for serverless functions in this directory.
  directory = "netlify/functions"
  
[functions."analyze-images"]
  timeout = 30
  memory = 1024
